from __future__ import annotations

import re
from collections.abc import Callable, Iterable, Mapping, Sequence
from datetime import timedelta
from pathlib import PurePosixPath

from untaped_orchestration.application.ports import (
    MANAGED_VIEW_PATHS,
    FederatedSnapshot,
    StoreSnapshot,
    ViewRenderer,
)
from untaped_orchestration.domain.graph import (
    DecisionNode,
    DecisionRef,
    GraphCompleteness,
    GraphState,
    TaskNode,
    decision_state,
)
from untaped_orchestration.domain.models import ActiveTask, Decision, LinkRelation, TaskStage
from untaped_orchestration.domain.ordering import TaskOrderItem, sort_tasks
from untaped_orchestration.domain.time import local_calendar_date

_EMPTY = "_No items._\n"
_MISSING = "—"
_LINE_BREAKS = re.compile(r"[\r\n]+")


def _root(value: object | None) -> str | None:
    if value is None:
        return None
    root = getattr(value, "root", None)
    return str(root if root is not None else value)


def _escape(value: str) -> str:
    value = _LINE_BREAKS.sub("<br>", value)
    value = value.replace("\\", "\\\\")
    return value.replace("|", "\\|")


def _cell(value: object | None, *, identifier: bool = False) -> str:
    rendered = _root(value)
    if rendered is None or rendered == "":
        return _MISSING
    escaped = _escape(rendered)
    return f"`{escaped}`" if identifier else escaped


def _values(values: Iterable[object]) -> str:
    rendered = ", ".join(_root(value) or "" for value in values)
    return _escape(rendered) if rendered else _MISSING


def _prefix(snapshot: StoreSnapshot, title: str) -> str:
    if snapshot.store is None:
        raise ValueError("cannot render views for an invalid store configuration")
    return (
        "<!-- Generated by untaped-orchestration; do not edit. -->\n"
        f"# {snapshot.store.name} — {title}\n\n"
        f"Store revision: `{snapshot.store_revision.root}`\n\n"
    )


def _table(headers: Sequence[str], rows: Sequence[Sequence[str]]) -> str:
    if not rows:
        return _EMPTY
    header = "| " + " | ".join(headers) + " |\n"
    separator = "|" + "|".join("---" for _ in headers) + "|\n"
    values = "".join("| " + " | ".join(row) + " |\n" for row in rows)
    return header + separator + values


def _task_review_due(snapshot: StoreSnapshot, task: ActiveTask) -> object | None:
    if task.review_on is not None:
        return task.review_on
    assert snapshot.store is not None
    if task.stage is TaskStage.INBOX:
        baseline = task.reviewed_at or task.created_at
        days = snapshot.store.curation.inbox_review_days
    elif task.stage is TaskStage.IN_PROGRESS:
        assert task.started_at is not None
        baseline = task.reviewed_at or task.started_at
        days = snapshot.store.curation.in_progress_review_days
    else:
        return None
    local = local_calendar_date(baseline, snapshot.store.timezone).as_date()
    return (local + timedelta(days=days)).isoformat()


def _task_rows(
    snapshot: StoreSnapshot,
    ordered: Sequence[ActiveTask],
    *,
    stages: frozenset[TaskStage],
    row: Callable[[ActiveTask], Sequence[str]],
) -> list[Sequence[str]]:
    return [row(task) for task in ordered if task.stage in stages]


def _roadmap_rows(
    snapshot: StoreSnapshot,
    ordered: Sequence[ActiveTask],
    row: Callable[[ActiveTask], Sequence[str]],
) -> list[Sequence[str]]:
    return [
        row(task)
        for stage in (TaskStage.IN_PROGRESS, TaskStage.PLANNED)
        for task in ordered
        if task.stage is stage
    ]


def _graph(snapshot: StoreSnapshot) -> GraphState:
    if snapshot.store is None:
        raise ValueError("cannot render views for an invalid store configuration")
    tasks = tuple(
        TaskNode(snapshot.store.id, record.path.as_posix(), record.metadata)
        for record in snapshot.records
        if not isinstance(record.metadata, Decision)
    )
    decisions = tuple(
        DecisionNode(snapshot.store.id, record.path.as_posix(), record.metadata)
        for record in snapshot.records
        if isinstance(record.metadata, Decision)
    )
    return GraphState(
        tasks=tasks,
        decisions=decisions,
        completeness=GraphCompleteness(
            complete=True,
            known_store_ids=(snapshot.store.id,),
        ),
    )


def _decision_rows(snapshot: StoreSnapshot) -> list[Sequence[str]]:
    graph = _graph(snapshot)
    incoming: dict[str, str] = {}
    for node in graph.decisions:
        for link in node.decision.links:
            if link.relation is LinkRelation.SUPERSEDES:
                incoming[link.target.root] = node.decision.id.root
    state_order = {"active": 0, "superseded": 1, "retired": 2}
    values: list[tuple[tuple[object, ...], Sequence[str]]] = []
    assert snapshot.store is not None
    for node in graph.decisions:
        state = decision_state(DecisionRef(snapshot.store.id, node.decision.id), graph).value
        decision = node.decision
        values.append(
            (
                (state_order[state], decision.title.casefold(), decision.id.root),
                (
                    _cell(decision.id, identifier=True),
                    _cell(decision.title),
                    state,
                    _values(decision.tags),
                    _cell(decision.review_on),
                    _cell(incoming.get(decision.id.root), identifier=True),
                ),
            )
        )
    return [row for _, row in sorted(values, key=lambda value: value[0])]


class MarkdownViewRenderer(ViewRenderer):
    def managed_paths(self) -> tuple[PurePosixPath, ...]:
        return MANAGED_VIEW_PATHS

    def expected(
        self, snapshot: StoreSnapshot | FederatedSnapshot
    ) -> Mapping[PurePosixPath, bytes]:
        if isinstance(snapshot, FederatedSnapshot):
            snapshot = snapshot.selected
        if snapshot.store is None:
            raise ValueError("cannot render views for an invalid store configuration")
        active = [
            record.metadata
            for record in snapshot.records
            if isinstance(record.metadata, ActiveTask)
        ]
        ordered = tuple(
            value.task
            for value in sort_tasks(
                tuple(TaskOrderItem(snapshot.store.id, task) for task in active)
            )
        )
        rendered: dict[PurePosixPath, bytes] = {}
        if snapshot.store.capabilities.active_tasks:
            roadmap = _roadmap_rows(
                snapshot,
                ordered,
                row=lambda task: (
                    _cell(task.id, identifier=True),
                    _cell(task.title),
                    task.stage.value,
                    task.priority.value,
                    _cell(task.parent, identifier=True),
                    _values(task.waiting_on),
                    _cell(_task_review_due(snapshot, task)),
                ),
            )
            backlog = _task_rows(
                snapshot,
                ordered,
                stages=frozenset({TaskStage.BACKLOG}),
                row=lambda task: (
                    _cell(task.id, identifier=True),
                    _cell(task.title),
                    task.priority.value,
                    _cell(task.parent, identifier=True),
                    _cell(task.revisit_when),
                    _cell(task.review_on),
                    _values(task.waiting_on),
                ),
            )
            inbox = _task_rows(
                snapshot,
                ordered,
                stages=frozenset({TaskStage.INBOX}),
                row=lambda task: (
                    _cell(task.id, identifier=True),
                    _cell(task.title),
                    task.priority.value,
                    _cell(task.parent, identifier=True),
                    _cell(_task_review_due(snapshot, task)),
                    _values(task.waiting_on),
                ),
            )
            rendered[PurePosixPath("views/roadmap.md")] = (
                _prefix(snapshot, "Roadmap")
                + _table(
                    ("ID", "Title", "Stage", "Priority", "Parent", "Waiting on", "Review due"),
                    roadmap,
                )
            ).encode()
            rendered[PurePosixPath("views/backlog.md")] = (
                _prefix(snapshot, "Backlog")
                + _table(
                    (
                        "ID",
                        "Title",
                        "Priority",
                        "Parent",
                        "Revisit when",
                        "Review on",
                        "Waiting on",
                    ),
                    backlog,
                )
            ).encode()
            rendered[PurePosixPath("views/inbox.md")] = (
                _prefix(snapshot, "Inbox")
                + _table(
                    ("ID", "Title", "Priority", "Parent", "Review due", "Waiting on"),
                    inbox,
                )
            ).encode()
        rendered[PurePosixPath("views/decisions.md")] = (
            _prefix(snapshot, "Decisions")
            + _table(
                ("ID", "Title", "State", "Tags", "Review on", "Successor"),
                _decision_rows(snapshot),
            )
        ).encode()
        return rendered
