from __future__ import annotations

from dataclasses import replace
from pathlib import Path, PurePosixPath

from tests.builders import DECISION_ID, STORE_ID, TASK_ID, decision_bytes, task_bytes, write_store
from untaped_orchestration.application.results import Completeness, FederatedSnapshot, LoadedRecord
from untaped_orchestration.domain.ids import DecisionId, StoreId
from untaped_orchestration.domain.models import Link, LinkRelation, TaskStage
from untaped_orchestration.infrastructure.codec import ItemCodec
from untaped_orchestration.infrastructure.filesystem import file_revision, location_from_root
from untaped_orchestration.infrastructure.repository import FilesystemStoreRepository
from untaped_orchestration.infrastructure.views import MarkdownViewRenderer

SECOND_TASK_ID = "tsk_019f0000000070008000000000000011"
THIRD_TASK_ID = "tsk_019f0000000070008000000000000012"
SECOND_DECISION_ID = "dec_019f0000000070008000000000000002"


def _validated_copy(model, **updates):
    values = model.model_dump(by_alias=True)
    values.update(updates)
    return type(model).model_validate(values)


def _empty_snapshot(tmp_path: Path, *, active_tasks: bool = True):
    root = write_store(tmp_path / "repository")
    if not active_tasks:
        store = root.joinpath("store.toml")
        store.write_bytes(
            store.read_bytes().replace(b"active_tasks = true", b"active_tasks = false")
        )
    return FilesystemStoreRepository().load_local(location_from_root(root), headers_only=False)


def _record(path: str, raw: bytes, *, metadata=None, body: bytes | None = None) -> LoadedRecord:
    relative = PurePosixPath(path)
    fixture_path = relative
    if metadata is not None:
        fixture_path = PurePosixPath(
            f"decisions/{DECISION_ID}-choice.md"
            if relative.parts[0] == "decisions"
            else f"tasks/{TASK_ID}-task.md"
        )
    parsed = ItemCodec().parse(raw, relative_path=fixture_path)
    return LoadedRecord(
        path=relative,
        revision=file_revision(raw),
        metadata=metadata or parsed.metadata,
        body=parsed.body if body is None else body,
    )


def test_empty_task_store_views_are_byte_exact_and_end_with_one_lf(tmp_path: Path) -> None:
    snapshot = _empty_snapshot(tmp_path)

    rendered = MarkdownViewRenderer().expected(snapshot)

    assert rendered == {
        PurePosixPath("views/roadmap.md"): (
            b"<!-- Generated by untaped-orchestration; do not edit. -->\n"
            b"# Untaped orchestration hub \xe2\x80\x94 Roadmap\n\n"
            + f"Store revision: `{snapshot.store_revision.root}`\n\n".encode()
            + b"_No items._\n"
        ),
        PurePosixPath("views/backlog.md"): (
            b"<!-- Generated by untaped-orchestration; do not edit. -->\n"
            b"# Untaped orchestration hub \xe2\x80\x94 Backlog\n\n"
            + f"Store revision: `{snapshot.store_revision.root}`\n\n".encode()
            + b"_No items._\n"
        ),
        PurePosixPath("views/inbox.md"): (
            b"<!-- Generated by untaped-orchestration; do not edit. -->\n"
            b"# Untaped orchestration hub \xe2\x80\x94 Inbox\n\n"
            + f"Store revision: `{snapshot.store_revision.root}`\n\n".encode()
            + b"_No items._\n"
        ),
        PurePosixPath("views/decisions.md"): (
            b"<!-- Generated by untaped-orchestration; do not edit. -->\n"
            b"# Untaped orchestration hub \xe2\x80\x94 Decisions\n\n"
            + f"Store revision: `{snapshot.store_revision.root}`\n\n".encode()
            + b"_No items._\n"
        ),
    }
    assert all(raw.endswith(b"\n") and not raw.endswith(b"\n\n") for raw in rendered.values())


def test_decision_only_store_renders_only_the_decisions_view(tmp_path: Path) -> None:
    snapshot = _empty_snapshot(tmp_path, active_tasks=False)

    assert tuple(MarkdownViewRenderer().expected(snapshot)) == (
        PurePosixPath("views/decisions.md"),
    )


def test_nonempty_task_views_pin_columns_order_due_dates_and_cell_escaping(tmp_path: Path) -> None:
    snapshot = _empty_snapshot(tmp_path)
    base = _record(f"tasks/{TASK_ID}-task.md", task_bytes()).metadata
    assert base.kind.value == "task"
    inbox = _validated_copy(
        base,
        title="Inbox\r\nneeds \\ review | now",
        created_at="2026-01-01T12:00:00.000Z",
        stage=TaskStage.INBOX,
        rank=2000,
        waiting_on=("legal", "ops"),
    )
    planned = _validated_copy(
        base,
        id=SECOND_TASK_ID,
        title="Planned",
        stage=TaskStage.PLANNED,
        rank=1000,
        review_on="2026-02-03",
    )
    progress = _validated_copy(
        base,
        id=THIRD_TASK_ID,
        title="Progress",
        stage=TaskStage.IN_PROGRESS,
        rank=3000,
        started_at="2026-01-02T12:00:00.000Z",
        parent=SECOND_TASK_ID,
        waiting_on=("vendor",),
    )
    backlog = _validated_copy(
        base,
        id="tsk_019f0000000070008000000000000013",
        title="Backlog",
        stage=TaskStage.BACKLOG,
        rank=4000,
        revisit_when="API stabilizes",
        review_on="2026-04-05",
    )
    records = (
        _record(f"tasks/{inbox.id.root}-inbox.md", task_bytes(), metadata=inbox),
        _record(f"tasks/{planned.id.root}-planned.md", task_bytes(), metadata=planned),
        _record(f"tasks/{progress.id.root}-progress.md", task_bytes(), metadata=progress),
        _record(f"tasks/{backlog.id.root}-backlog.md", task_bytes(), metadata=backlog),
    )
    snapshot = replace(snapshot, records=records)

    rendered = MarkdownViewRenderer().expected(snapshot)

    prefix = (
        "<!-- Generated by untaped-orchestration; do not edit. -->\n"
        "# Untaped orchestration hub \u2014 {}\n\n"
        f"Store revision: `{snapshot.store_revision.root}`\n\n"
    )
    assert rendered[PurePosixPath("views/roadmap.md")].decode() == prefix.format("Roadmap") + (
        "| ID | Title | Stage | Priority | Parent | Waiting on | Review due |\n"
        "|---|---|---|---|---|---|---|\n"
        f"| `{THIRD_TASK_ID}` | Progress | in-progress | normal | "
        f"`{SECOND_TASK_ID}` | vendor | 2026-01-16 |\n"
        f"| `{SECOND_TASK_ID}` | Planned | planned | normal | \u2014 | \u2014 | 2026-02-03 |\n"
    )
    assert rendered[PurePosixPath("views/backlog.md")].decode() == prefix.format("Backlog") + (
        "| ID | Title | Priority | Parent | Revisit when | Review on | Waiting on |\n"
        "|---|---|---|---|---|---|---|\n"
        f"| `{backlog.id.root}` | Backlog | normal | \u2014 | "
        "API stabilizes | 2026-04-05 | \u2014 |\n"
    )
    assert rendered[PurePosixPath("views/inbox.md")].decode() == prefix.format("Inbox") + (
        "| ID | Title | Priority | Parent | Review due | Waiting on |\n"
        "|---|---|---|---|---|---|\n"
        f"| `{TASK_ID}` | Inbox<br>needs \\\\ review \\| now | normal | \u2014 | "
        "2026-01-08 | legal, ops |\n"
    )


def test_decision_rows_are_local_state_ordered_and_show_the_unique_successor(
    tmp_path: Path,
) -> None:
    snapshot = _empty_snapshot(tmp_path)
    first_record = _record(f"decisions/{DECISION_ID}-choice.md", decision_bytes())
    predecessor = _validated_copy(first_record.metadata, title="zeta", tags=("one", "two"))
    successor = _validated_copy(
        first_record.metadata,
        id=SECOND_DECISION_ID,
        title="Alpha",
        tags=(),
        links=(
            Link(
                relation=LinkRelation.SUPERSEDES,
                target_store_id=StoreId(STORE_ID),
                target=DecisionId(DECISION_ID),
            ),
        ),
    )
    retired = _validated_copy(
        first_record.metadata,
        id="dec_019f0000000070008000000000000003",
        title="beta",
        tags=(),
        retired_at="2026-02-01T00:00:00.000Z",
        retire_note="No longer applies",
    )
    snapshot = replace(
        snapshot,
        records=(
            _record(
                f"decisions/{predecessor.id.root}-zeta.md", decision_bytes(), metadata=predecessor
            ),
            _record(
                f"decisions/{successor.id.root}-alpha.md", decision_bytes(), metadata=successor
            ),
            _record(f"decisions/{retired.id.root}-beta.md", decision_bytes(), metadata=retired),
        ),
    )

    rendered = MarkdownViewRenderer().expected(snapshot)[PurePosixPath("views/decisions.md")]

    assert rendered.decode().endswith(
        "| ID | Title | State | Tags | Review on | Successor |\n"
        "|---|---|---|---|---|---|\n"
        f"| `{SECOND_DECISION_ID}` | Alpha | active | \u2014 | \u2014 | \u2014 |\n"
        f"| `{DECISION_ID}` | zeta | superseded | one, two | \u2014 | `{SECOND_DECISION_ID}` |\n"
        f"| `{retired.id.root}` | beta | retired | \u2014 | \u2014 | \u2014 |\n"
    )


def test_views_never_include_bodies_or_another_store_snapshot(tmp_path: Path) -> None:
    snapshot = _empty_snapshot(tmp_path)
    local = _record(f"decisions/{DECISION_ID}-choice.md", decision_bytes(), body=b"SECRET BODY")
    foreign = local.metadata.model_copy(update={"id": SECOND_DECISION_ID, "title": "Foreign"})
    selected = replace(snapshot, records=(local,))
    foreign_snapshot = replace(
        _empty_snapshot(tmp_path / "foreign"),
        records=(
            _record(
                f"decisions/{SECOND_DECISION_ID}-foreign.md",
                decision_bytes(),
                metadata=foreign,
                body=b"FOREIGN SECRET",
            ),
        ),
    )
    federated = FederatedSnapshot(selected, (selected, foreign_snapshot), Completeness())

    raw = b"".join(MarkdownViewRenderer().expected(federated).values())

    assert b"SECRET BODY" not in raw
    assert b"FOREIGN SECRET" not in raw
    assert foreign.title.encode() not in raw
